import { StyleSheet } from 'react-native';

import { profileShadow, profileTheme } from '@/theme/profileTheme';

export const providerDetailStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: profileTheme.colors.background,
  },
  content: {
    padding: profileTheme.spacing.page,
    paddingBottom: 28,
    gap: profileTheme.spacing.sectionGap,
  },
  heroRow: {
    gap: 2,
  },
  heroEyebrow: {
    color: '#5f7593',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  heroTitle: {
    color: '#12263f',
    fontSize: 25,
    fontWeight: '800',
  },
  heroSubtitle: {
    color: '#5f7593',
    fontSize: 14,
    lineHeight: 20,
  },
  headerCard: {
    backgroundColor: profileTheme.colors.surface,
    borderRadius: profileTheme.radius.lg,
    borderWidth: 1,
    borderColor: profileTheme.colors.border,
    padding: profileTheme.spacing.cardPadding,
    gap: 8,
    ...profileShadow,
  },
  headerTopRow: {
    flexDirection: 'row',
    gap: 10,
  },
  headerTextWrap: {
    flex: 1,
    gap: 2,
  },
  avatar: {
    width: 58,
    height: 58,
    borderRadius: 999,
    backgroundColor: '#dbe6f5',
  },
  providerName: {
    fontSize: 19,
    fontWeight: '800',
    color: profileTheme.colors.title,
  },
  professionLine: {
    color: '#355272',
    fontWeight: '700',
  },
  cityLine: {
    color: profileTheme.colors.body,
  },
  bioText: {
    color: '#304862',
    lineHeight: 19,
    fontSize: 13,
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  metricBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: profileTheme.colors.borderSoft,
    borderRadius: profileTheme.radius.sm,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: profileTheme.colors.surfaceMuted,
  },
  metricValue: {
    color: profileTheme.colors.title,
    fontWeight: '800',
    fontSize: 16,
  },
  metricLabel: {
    color: profileTheme.colors.body,
    fontSize: 11,
  },
  ratingLineWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  starsIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  ratingMetaText: {
    color: '#31557f',
    fontWeight: '700',
  },
  badgesWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  badge: {
    backgroundColor: '#f2f6fc',
    borderColor: '#d8e2ef',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  badgeText: {
    fontWeight: '600',
    fontSize: 10,
  },
  servicesCard: {
    backgroundColor: profileTheme.colors.surface,
    borderRadius: profileTheme.radius.lg,
    borderWidth: 1,
    borderColor: profileTheme.colors.border,
    padding: profileTheme.spacing.cardPadding,
    gap: 10,
    ...profileShadow,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: profileTheme.colors.title,
  },
  sectionSubtitle: {
    color: profileTheme.colors.body,
    lineHeight: 19,
    fontSize: 13,
  },
  dropdownToggleButton: {
    borderWidth: 1,
    borderColor: '#d8e2ef',
    backgroundColor: '#f7fbff',
    borderRadius: profileTheme.radius.md,
    paddingHorizontal: 12,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  dropdownToggleContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    width: '100%',
  },
  dropdownToggleButtonText: {
    color: '#244a74',
    fontWeight: '700',
    fontSize: 13,
    flex: 1,
  },
  dropdownHintText: {
    color: '#6a809c',
    fontSize: 12,
    lineHeight: 18,
    marginTop: -2,
  },
  serviceItem: {
    borderWidth: 1,
    borderColor: profileTheme.colors.borderSoft,
    borderRadius: profileTheme.radius.md,
    padding: 10,
    gap: 6,
    backgroundColor: profileTheme.colors.surfaceMuted,
  },
  serviceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  serviceTitle: {
    flex: 1,
    fontWeight: '800',
    color: '#12263f',
  },
  categoryChip: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: '#c4d3e7',
    backgroundColor: '#eef4fd',
  },
  categoryChipText: {
    fontWeight: '700',
    fontSize: 10,
  },
  serviceDescription: {
    color: '#304862',
    lineHeight: 19,
    fontSize: 13,
  },
  servicePrice: {
    color: '#1d4f82',
    fontWeight: '800',
  },
  serviceButton: {
    alignSelf: 'flex-start',
    backgroundColor: profileTheme.colors.primary,
    borderRadius: profileTheme.radius.sm,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  serviceButtonText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 13,
  },
  emptyStateCard: {
    borderWidth: 1,
    borderColor: '#e4ebf4',
    borderRadius: 14,
    backgroundColor: '#fbfdff',
    padding: 14,
    gap: 3,
  },
  emptyStateTitle: {
    color: '#183b63',
    fontWeight: '700',
    fontSize: 14,
  },
  emptyStateText: {
    color: '#65809d',
    fontSize: 12,
    lineHeight: 18,
  },
  reviewsCard: {
    backgroundColor: profileTheme.colors.surface,
    borderRadius: profileTheme.radius.lg,
    borderWidth: 1,
    borderColor: profileTheme.colors.border,
    padding: profileTheme.spacing.cardPadding,
    gap: 10,
    ...profileShadow,
  },
  reviewCard: {
    borderWidth: 1,
    borderColor: profileTheme.colors.borderSoft,
    borderRadius: profileTheme.radius.md,
    padding: 10,
    gap: 6,
    backgroundColor: profileTheme.colors.surfaceMuted,
  },
  reviewHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  reviewerName: {
    fontWeight: '800',
    color: profileTheme.colors.title,
    flex: 1,
  },
  reviewDate: {
    color: profileTheme.colors.body,
    fontSize: 12,
  },
  reviewServiceChip: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: '#d4e2f0',
    backgroundColor: '#eef4fc',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  reviewServiceChipText: {
    color: '#2f557d',
    fontWeight: '700',
    fontSize: 11,
  },
  reviewRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  reviewRatingValue: {
    color: '#31557f',
    fontWeight: '700',
    fontSize: 12,
  },
  reviewComment: {
    color: '#2f4764',
    lineHeight: 19,
    fontSize: 13,
  },
  reviewPhotosRow: {
    gap: 8,
  },
  reviewPhoto: {
    width: 112,
    height: 84,
    borderRadius: 10,
    backgroundColor: '#dbe6f5',
  },
  loadMoreButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#cad9ea',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    backgroundColor: '#f6faff',
  },
  loadMoreButtonText: {
    color: '#2b5583',
    fontWeight: '800',
    fontSize: 13,
  },
  loadMoreRow: {
    flexDirection: 'row',
    gap: 8,
  },
  loadLessButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#d8e2ef',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    backgroundColor: '#fff',
  },
  loadLessButtonText: {
    color: '#47688a',
    fontWeight: '700',
    fontSize: 13,
  },
  notFoundWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: profileTheme.colors.background,
  },
  notFoundTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: profileTheme.colors.title,
    textAlign: 'center',
  },
  notFoundText: {
    marginTop: 6,
    color: profileTheme.colors.body,
    textAlign: 'center',
  },
});
