import { StyleSheet } from 'react-native';

import { profileShadow, profileTheme } from '@/theme/profileTheme';

export const paymentStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: profileTheme.colors.background,
  },
  content: {
    padding: 16,
    paddingBottom: 30,
    gap: 14,
  },
  heroRow: {
    gap: 2,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  heroEyebrow: {
    color: '#5f7593',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  heroTitle: {
    color: '#12263f',
    fontSize: 27,
    fontWeight: '800',
  },
  heroSubtitle: {
    color: '#5f7593',
    fontSize: 14,
    lineHeight: 20,
  },
  card: {
    borderWidth: 1,
    borderColor: profileTheme.colors.border,
    borderRadius: 16,
    backgroundColor: profileTheme.colors.surface,
    padding: 16,
    gap: 12,
    ...profileShadow,
  },
  title: {
    color: '#12263f',
    fontSize: 21,
    fontWeight: '800',
  },
  subtitle: {
    color: '#5f7593',
    lineHeight: 20,
  },
  helper: {
    color: '#6a809c',
    fontSize: 12,
    marginBottom: 4,
  },
  emptyState: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e4ebf4',
    backgroundColor: '#fbfdff',
    padding: 14,
    gap: 3,
  },
  emptyTitle: {
    color: '#183b63',
    fontWeight: '700',
    fontSize: 14,
  },
  emptyText: {
    color: '#65809d',
    fontSize: 12,
    lineHeight: 17,
  },
  paymentCardWrap: {
    borderWidth: 1,
    borderColor: '#e4ebf4',
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#fbfdff',
  },
  paymentRow: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  dropdownToggleButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#d5e2f1',
    backgroundColor: '#ffffff',
    borderRadius: 10,
  },
  paymentInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  cardIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#e6f0fb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentInfo: {
    flex: 1,
    gap: 2,
  },
  paymentBrand: {
    color: '#17395f',
    fontSize: 14,
    fontWeight: '700',
  },
  paymentHolder: {
    color: '#65809d',
    fontSize: 12,
  },
  dropdownContent: {
    borderTopWidth: 1,
    borderTopColor: '#e4ebf4',
    padding: 12,
    gap: 10,
    backgroundColor: '#f8fbff',
  },
  dropdownHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dropdownTitle: {
    color: '#17395f',
    fontWeight: '700',
  },
  eyeButton: {
    width: 30,
    height: 30,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#dbe5f2',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailLabel: {
    color: '#607a97',
    fontSize: 12,
  },
  detailValue: {
    color: '#183b63',
    fontSize: 13,
    fontWeight: '700',
  },
  removeInDropdownButton: {
    marginTop: 4,
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#ebc7c7',
    backgroundColor: '#fff3f3',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  removeInDropdownContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  removeInDropdownText: {
    color: '#9a3d3d',
    fontWeight: '700',
    fontSize: 13,
    flexShrink: 1,
  },
  headerPlusButton: {
    width: 34,
    height: 34,
    borderRadius: 11,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0,
    marginRight: 0,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(8, 24, 44, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#d8e6f5',
    backgroundColor: '#ffffff',
    padding: 16,
    gap: 10,
    ...profileShadow,
  },
  modalTitle: {
    color: '#17395f',
    fontSize: 19,
    fontWeight: '800',
  },
  modalSubtitle: {
    color: '#5f7593',
    lineHeight: 20,
    fontSize: 13,
  },
  passwordInput: {
    borderWidth: 1,
    borderColor: '#d8e6f5',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
    color: '#17395f',
    backgroundColor: '#f8fbff',
  },
  cardFormRow: {
    flexDirection: 'row',
    gap: 8,
  },
  cardFormHalfInput: {
    flex: 1,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  cancelButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d7e3f1',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    backgroundColor: '#f7fbff',
  },
  cancelButtonText: {
    color: '#47688a',
    fontWeight: '700',
    fontSize: 13,
  },
  confirmButton: {
    flex: 1,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    backgroundColor: profileTheme.colors.primary,
  },
  confirmButtonText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 13,
  },
});
