import { StyleSheet } from 'react-native';

import { profileShadow, profileTheme } from '@/theme/profileTheme';

export const chatStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: profileTheme.colors.background,
  },
  ambientTopOrb: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 999,
    backgroundColor: 'rgba(190, 216, 243, 0.32)',
    top: -72,
    right: -58,
  },
  ambientBottomOrb: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 999,
    backgroundColor: 'rgba(207, 225, 245, 0.30)',
    bottom: 80,
    left: -48,
  },
  headerCard: {
    backgroundColor: profileTheme.colors.surface,
    borderWidth: 1,
    borderColor: '#d8e2ef',
    marginHorizontal: 12,
    marginTop: 10,
    borderRadius: 16,
    padding: 14,
    gap: 10,
    ...profileShadow,
  },
  headerGrip: {
    alignSelf: 'center',
    width: 38,
    height: 4,
    borderRadius: 999,
    backgroundColor: '#d2deeb',
    marginBottom: 2,
  },
  messagesScroll: {
    flex: 1,
  },
  messagesSectionWrap: {
    flex: 1,
  },
  messagesContent: {
    paddingHorizontal: 12,
    paddingTop: 14,
    paddingBottom: 8,
    gap: 10,
  },
  inputBarWrap: {
    backgroundColor: profileTheme.colors.surface,
    borderTopWidth: 1,
    borderColor: '#dce5f1',
    paddingTop: 8,
    paddingHorizontal: 12,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    ...profileShadow,
  },
  attachmentPreviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    gap: 8,
  },
  attachmentThumb: {
    width: 56,
    height: 56,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ccd8ea',
  },
  attachmentFileChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#eef4fc',
    borderWidth: 1,
    borderColor: '#c5d8ef',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  attachmentFileName: {
    flex: 1,
    color: '#15599a',
    fontSize: 13,
    fontWeight: '600',
  },
  attachmentRemove: {
    padding: 2,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingBottom: 4,
    gap: 8,
  },
  attachButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  serviceName: {
    color: '#1d3d61',
    fontWeight: '800',
    fontSize: 17,
  },
  participantsText: {
    color: '#5a6e88',
    lineHeight: 20,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  statusRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusLabel: {
    color: '#4f617a',
    fontWeight: '700',
  },
  statusBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusBadgeOpen: {
    backgroundColor: '#e9f5ff',
    borderColor: '#bed9f3',
  },
  statusBadgeMediation: {
    backgroundColor: '#fff6e7',
    borderColor: '#f0d6a0',
  },
  statusBadgeClosed: {
    backgroundColor: '#f3f4f6',
    borderColor: '#d5d9df',
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  statusBadgeTextOpen: {
    color: '#18558e',
  },
  statusBadgeTextMediation: {
    color: '#916116',
  },
  statusBadgeTextClosed: {
    color: '#5f6b7a',
  },
  messageInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ccd8ea',
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    lineHeight: 20,
    minHeight: 42,
    maxHeight: 102,
    backgroundColor: '#f7f9fc',
    color: '#12233b',
    textAlignVertical: 'top',
  },
  inputDisabled: {
    backgroundColor: '#f0f3f7',
    color: '#7a8aa1',
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#15599a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonDisabled: {
    backgroundColor: '#a3bcd8',
  },
  startButton: {
    backgroundColor: '#145a9b',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  startButtonText: {
    color: '#fff',
    fontWeight: '800',
  },
  closedNotice: {
    borderWidth: 1,
    borderColor: '#e3d4b0',
    backgroundColor: '#fff7e8',
    borderRadius: 12,
    padding: 10,
  },
  closedNoticeText: {
    color: '#7a5c1d',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
  },
  interventionButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff7eb',
    borderWidth: 1,
    borderColor: '#e9c97a',
    borderRadius: 18,
  },
  emptyText: {
    color: '#5f738e',
    textAlign: 'center',
    lineHeight: 20,
  },
  emptyChatCard: {
    marginTop: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dce5f1',
    borderRadius: 12,
    padding: 12,
    ...profileShadow,
  },
  messageRow: {
    flexDirection: 'row',
  },
  messageRowCurrentUser: {
    justifyContent: 'flex-end',
  },
  messageRowOther: {
    justifyContent: 'flex-start',
  },
  messageBubble: {
    maxWidth: '80%',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 4,
    ...profileShadow,
  },
  messageBubbleCurrentUser: {
    backgroundColor: '#dbeafe',
    borderColor: '#bfdbfe',
    borderBottomRightRadius: 4,
  },
  messageBubbleProvider: {
    backgroundColor: '#ffffff',
    borderColor: '#dde5f2',
    borderBottomLeftRadius: 4,
  },
  messageBubbleAdmin: {
    backgroundColor: '#fff9eb',
    borderColor: '#efd090',
    borderBottomLeftRadius: 4,
  },
  messageSender: {
    color: '#1f3c5e',
    fontWeight: '700',
    fontSize: 12,
  },
  messageText: {
    color: '#233e5e',
    lineHeight: 20,
  },
  bubbleAttachment: {
    marginBottom: 2,
  },
  attachmentHint: {
    marginTop: 4,
    color: '#5c6f86',
    fontSize: 11,
    fontWeight: '600',
  },
  bubbleImage: {
    width: 200,
    height: 140,
    borderRadius: 8,
  },
  bubbleFileChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#eef4fc',
    borderWidth: 1,
    borderColor: '#c5d8ef',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    maxWidth: 220,
  },
  bubbleFileName: {
    flex: 1,
    color: '#15599a',
    fontSize: 13,
    fontWeight: '600',
  },
  messageFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 2,
  },
  messageDate: {
    color: '#687b94',
    fontSize: 11,
  },
  readReceiptWrap: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkSecond: {
    marginLeft: -7,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(10, 18, 31, 0.45)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: profileTheme.colors.surface,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    padding: 18,
    gap: 10,
    ...profileShadow,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#12233b',
  },
  modalSubtitle: {
    color: '#506178',
    lineHeight: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccd8ea',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    backgroundColor: '#fff',
    color: '#12233b',
  },
  modalInput: {
    minHeight: 110,
    textAlignVertical: 'top',
  },
  modalActionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  modalSecondaryButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#cfd9e6',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    backgroundColor: '#fff',
  },
  modalSecondaryButtonText: {
    color: '#27496b',
    fontWeight: '700',
  },
  modalPrimaryButton: {
    flex: 1,
    backgroundColor: '#15599a',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  modalPrimaryButtonText: {
    color: '#fff',
    fontWeight: '800',
  },
  notFoundWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: '#f4f7fb',
  },
  notFoundTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#12233b',
    textAlign: 'center',
  },
  notFoundText: {
    marginTop: 6,
    color: '#4f617a',
    textAlign: 'center',
  },
  viewerScreen: {
    flex: 1,
    backgroundColor: profileTheme.colors.background,
  },
  viewerHeader: {
    height: 60,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderColor: '#dde5f2',
    backgroundColor: profileTheme.colors.surface,
  },
  viewerTitle: {
    flex: 1,
    marginRight: 10,
    color: '#12233b',
    fontSize: 15,
    fontWeight: '700',
  },
  viewerCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#eef3fa',
  },
  viewerBody: {
    flex: 1,
  },
  viewerWebView: {
    flex: 1,
    backgroundColor: '#fff',
  },
  viewerLoadingLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.65)',
  },
  viewerNoticeWrap: {
    padding: 10,
    borderTopWidth: 1,
    borderColor: '#dde5f2',
    backgroundColor: '#fff8e8',
  },
  viewerNoticeText: {
    color: '#7a5c1d',
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
  },
});
